title: Computer Music Conference Deadlines # (Maintained by @ldzhangyx)
email: ldzhangyx@outlook.com
description: Countdowns to computer music conference deadlines
author: Yixiao Zhang

domain: "yixiao-music.github.io"
baseurl: ""

github_username: yixiao-music
github_repo: yixiao-music.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']